### ISSUE TITLE
GermanWordSplitter NPE when accessing disambiguator

### ISSUE THREAD

**Issue by simasch** [danielnaber/jwordsplitter#13] opened 2017-08-09 09:29 UTC
disambiguator is null when using the new constructor.

**Comment by danielnaber** [comment] 2017-08-09 11:05
Should be fixed, I actually forgot to call `init()`, which was probably also the cause for #12.

**Closed by danielnaber** 2017-08-09 11:05 UTC

**Comment by simasch** [comment] 2017-08-09 11:08
But init() will call getWordList() and will load the EmbeddedGermanDictonary.

    protected Set<String> getWordList() {
        return EmbeddedGermanDictionary.getWords();
    }

Is this correct?

**Comment by danielnaber** [comment] 2017-08-09 11:39
Using the embedded dictionary for `GermanInterfixDisambiguator` seems correct - that's not the main dictionary, but rather a (very simple) attempt to remove ambiguities.

**Comment by simasch** [comment] 2017-08-09 11:41
Ok. Got you
Thanks.
